#!/usr/bin/env bash

set -e # exit on first error

echo "--- running tests ---"
python -m unittest discover --pattern="*_test.py"
echo ""

echo "--- running mypy ---"
mypy . --enable-incomplete-feature=Unpack
echo ""

echo "--- running black ---"
black .
echo ""

echo "--- running ruff ---"
ruff check . && echo "OK"
echo ""
